# Generated by Django 5.2.4 on 2025-09-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0002_auto_20250905_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
