# Generated by Django 5.2.4 on 2025-07-30 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='action',
            field=models.CharField(choices=[('subscribed', 'Subscribed'), ('cancelled', 'Cancelled')], default='subscribed', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
