# Generated by Django 5.2.4 on 2025-08-04 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionrenew'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionrenew',
            old_name='User_subscription',
            new_name='user_subscription',
        ),
        migrations.AddField(
            model_name='subscriptionrenew',
            name='renewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptionrenew',
            name='renewed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
