# Generated by Django 5.2.4 on 2025-08-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_rename_user_subscription_subscriptionrenew_user_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrenew',
            name='renewed_at_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
