# Generated by Django 5.2.4 on 2025-09-18 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='No address', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default='noemail@example.com', max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, default='https://example.com/logo.png', null=True, upload_to='')),
                ('phone', models.CharField(blank=True, default='0000000000', max_length=20, null=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_profiles/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='business_profiles/banners/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_panel_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
