# Generated by Django 5.2.4 on 2025-09-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='business/banners/'),
        ),
    ]
