# Generated by Django 5.2.4 on 2025-08-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, default='https://example.com/logo.png', null=True, upload_to=''),
        ),
    ]
