# Generated by Django 5.2.4 on 2025-08-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Phone',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
