# Generated by Django 5.2.4 on 2025-08-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
