# Generated by Django 5.2.4 on 2025-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
