"""
Django settings for daily_banner_app project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from decouple import config
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


#AUTH_USER_MODEL= 'accounts.CustomUser'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q!q)1j=fziwav6ic%$=k3@9r+^=q3#p_s9pz@3n3e!s=y$h1yv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SITE_ID= 1
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts.apps.AccountsConfig',
    'django.contrib.sites',
        
    #other apps
    'corsheaders',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    #'dj-database-url',


    #external apps
    #'accounts',
    'subscription',
    'admin_panel',
    'banner',
    'mediafiles',    
    'business_panel',
    'business_profile',
    'transactions',
    'greetings',
    'dashboard',
]

AUTH_USER_MODEL = 'accounts.CompanyDetails'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    #'accounts.middleware.CookieToAuthorizationMiddleware',

]

ROOT_URLCONF = 'daily_banner_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'daily_banner_app.wsgi.application'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR , 'media')

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'daily_banner_db',
#         'USER': 'banner_user',
#         'PASSWORD': 'DailyBannerApp01',
#         'HOST': 'postgresql://daily_banner_app_user:ISNQtyeICuB8oa0gw9bNQBqCSvwQIHst@dpg-d2e4kaggjchc73e13om0-a.oregon-postgres.render.com/daily_banner_app',  # use your actual host here
#         'PORT': '5432',
#         'OPTIONS': {
#             'sslmode': 'require'
#         }
#     }
# }


DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL',cast=str, default='sqlite:///daily_banner_app.db'),
    )
}
# =======
# >>>>>>> d63b02d (Added business and transaction API changes)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'daily_banner_db',
#         'USER':'banner_user',
#         'PASSWORD': 'DailyBannerApp01',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

# <<<<<<< HEAD
# >>>>>>> 0bcd095 (Ready for Render deployment with migrations)
# =======

# >>>>>>> d63b02d (Added business and transaction API changes)
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # No username field
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/' 
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT= os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
]

RAZORPAY_KEY_ID = 'rzp_test_cB8TVykpqqbxSn'

SOCIALACCOUNT_PROVIDERS = {
        'google': {
        #'APP': {
         #   'client_id': "33936103700-7a6110ahctl234qb52g0eie6t32qv53j.apps.googleusercontent.com",
          #  'secret': "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",}
            
        },
        'SCOPE': ['profile','email',], # type: ignore
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
}

GOOGLE_OAUTH_CLIENT_ID = os.getenv("33936103700-7a6110ahctl234qb52g0eie6t32qv53j.apps.googleusercontent.com")
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("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")

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'