# Generated by Django 5.2.4 on 2025-09-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='services',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='working_hours',
        ),
    ]
