# Generated by Django 5.2.4 on 2025-08-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='customizations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='greetingtemplate',
            name='default_background',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greetingtemplate',
            name='default_emojis',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='greetingtemplate',
            name='default_stickers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='greetingtemplate',
            name='default_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greetingtemplate',
            name='layout',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=50),
        ),
    ]
