# Generated by Django 5.2.4 on 2025-08-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0002_greeting_customizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingtemplate',
            name='language',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
