# Generated by Django 5.2.4 on 2025-08-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0003_greetingtemplate_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingtemplate',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
