# Generated by Django 5.2.4 on 2025-08-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0004_greetingtemplate_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingtemplate',
            name='customizations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='greetingtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='greetingtemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='greetingtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
