# Generated by Django 5.2.4 on 2025-08-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0006_greetingtemplatelike_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greetingtemplatelike',
            name='liked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
