# Generated by Django 5.2.4 on 2025-08-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0007_alter_greetingtemplatelike_liked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingtemplatelike',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
