# Generated by Django 5.2.4 on 2025-08-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0008_greetingtemplatelike_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingtemplate',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
