# Generated by Django 5.2.4 on 2025-08-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0009_greetingtemplate_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greetingtemplate',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
