# Generated by Django 5.2.4 on 2025-08-21 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0010_alter_greetingtemplate_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingtemplatedownload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
