# Generated by Django 5.2.4 on 2025-08-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0011_greetingtemplatedownload_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greetingtemplatedownload',
            name='downloaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
