# Generated by Django 5.2.4 on 2025-08-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0012_alter_greetingtemplatedownload_downloaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingtemplate',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
