# Generated by Django 5.2.4 on 2025-08-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0013_greetingtemplate_downloads_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greetingtemplate',
            name='downloads_count',
        ),
        migrations.AddField(
            model_name='greetingtemplate',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='greetingtemplate',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
