# Generated by Django 5.2.4 on 2025-08-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0014_remove_greetingtemplate_downloads_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greetingtemplate',
            name='is_downloaded',
        ),
        migrations.RemoveField(
            model_name='greetingtemplate',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='greetingtemplate',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
