# Generated by Django 5.2.4 on 2025-09-04 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('serif', 'Serif'), ('sans-serif', 'Sans-Serif'), ('display', 'Display'), ('script', 'Script')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], max_length=5)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('daily', 'Daily'), ('festival', 'Festival'), ('special', 'Special')], max_length=20)),
                ('template_image', models.ImageField(upload_to='templates/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='banners/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('custom_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='banner.template')),
            ],
        ),
    ]
