# Generated by Django 5.2.4 on 2025-08-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
