# Generated by Django 5.2.4 on 2025-07-29 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='custom_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='custom_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='banner.template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_image',
            field=models.ImageField(upload_to='templates/'),
        ),
    ]
