# Generated by Django 5.2.4 on 2025-08-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('serif', 'Serif'), ('sans-serif', 'Sans-Serif'), ('display', 'Display'), ('script', 'Script')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], max_length=5)),
                ('url', models.URLField()),
            ],
        ),
    ]
