# Generated by Django 5.2.4 on 2025-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_font'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='custom_logo',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='custom_photo',
        ),
        migrations.AddField(
            model_name='banner',
            name='custom_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='banner',
            name='custom_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
