# Generated by Django 5.2.4 on 2025-08-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_banner_banner_image_alter_banner_custom_logo_and_more'),
        ('banner', '0002_alter_template_template_image'),
    ]

    operations = [
    ]
