# Generated by Django 5.2.4 on 2025-09-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_remove_banner_banner_image_remove_banner_custom_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
